---
# Example execution:
#   -> ansible-playbook delete_protection_policies.yaml -e environment_key=nonprod -e site_key=qd5  -e nutanix_host=10.10.3.10 --vault-pass-file .vault-token  -e scenario=sc1
- name: Delete Protection Policies
  hosts: localhost
  vars_files:
    - "vars/{{ environment_key }}/{{ site_key }}/protectionpolicies/{{ scenario }}.yaml"
    - var_vault.yaml
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: "{{ nutanix_host }}"
      nutanix_username: "{{ nutanix_username }}"
      nutanix_password: "{{ nutanix_password }}"
      validate_certs: false
  tasks:
    #### Helper Task Operations
    - name: Fetch cluster uuids
      ansible.builtin.include_tasks: task_helpers/get_cluster_uuids.yaml
      vars:
        ntnx_cluster_list:
          - "{{ cluster_name }}"

    - name: Fetch availability zone IDs
      ansible.builtin.include_tasks: task_helpers/get_availability_zone_uuids.yaml
      vars:
        ntnx_availability_zones_list: "{{ availability_zones_list | default([]) }}"

    - name: Get Protection Policies and their IDs
      ansible.builtin.include_tasks: task_helpers/get_protection_policy_uuids.yaml
      vars:
        ntnx_protection_policies_list: "{{ protection_policies.keys() | list }}"

    #### Protection Policy Operations
    - name: Delete Protection Policies
      ansible.builtin.import_role:
        name: ntnx_protection_policies
        tasks_from: delete_protection_policies.yaml 