---
# Example execution:
#   -> ansible-playbook subnets.yaml -e environment_key=nonprod -e site_key=qd5 -e nutanix_host=10.10.3.10 --vault-pass-file .vault-token -e cluster_name=KSALAB-NX
- name: Create/Update Subnets
  hosts: localhost
  vars_files:
    - "vars/{{ environment_key }}/{{ site_key }}/var_subnet.yaml"
    - var_vault.yaml
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: "{{ nutanix_host }}"
      nutanix_username: "{{ nutanix_username }}"
      nutanix_password: "{{ nutanix_password }}"
      validate_certs: false
  tasks:
    #### Helper Task Operations
    - name: Fetch cluster uuids
      ansible.builtin.include_tasks: task_helpers/get_cluster_uuids.yaml
      vars:
        ntnx_cluster_list:
          - "{{ cluster_name }}"

    #### Subnet Operations
    - name: Check if subnet exists and if not, create it, if exists, update it
      ansible.builtin.include_role:
        name: ntnx_subnets
        tasks_from: create_update_subnet.yaml
      loop: "{{ subnets[cluster_name].keys() }}"
      vars:
        subnet_type: "{{ subnets[cluster_name][subnet_iter]['subnet_type'] }}"
        network_id: "{{ subnets[cluster_name][subnet_iter]['network_id'] }}"
        subnet_name: "{{ subnet_iter }}"
      loop_control:
        loop_var: subnet_iter
        label: "{{ subnets[cluster_name][subnet_iter] }}"
...